/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
module DIG_D_FF_1bit
#(
    parameter Default = 0
)
(
   input D,
   input C,
   output Q,
   output \~Q
);
    reg state;

    assign Q = state;
    assign \~Q = ~state;

    always @ (posedge C) begin
        state <= D;
    end

    initial begin
        state = Default;
    end
endmodule


module Mux_2x1
(
    input [0:0] sel,
    input in_0,
    input in_1,
    output reg out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module labtimer (
  input CLK,
  input SW,
  input B3,
  input B2,
  input B1,
  input B0,
  input HZ1,
  output [3:0] M10,
  output [3:0] M1,
  output [3:0] S10,
  output [3:0] S1
);
  wire [3:0] M10_temp;
  wire [3:0] M1_temp;
  wire [3:0] S10_temp;
  wire [3:0] S1_temp;
  wire s0;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  wire s69;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s80;
  wire s81;
  wire s82;
  wire s83;
  wire s84;
  wire s85;
  wire s86;
  wire s87;
  wire s88;
  wire s89;
  wire s90;
  wire s91;
  wire s92;
  wire s93;
  wire s94;
  wire s95;
  wire s96;
  wire s97;
  wire s98;
  wire s99;
  wire s100;
  wire s101;
  wire s102;
  wire s103;
  wire s104;
  wire s105;
  wire s106;
  wire s107;
  wire s108;
  wire s109;
  wire s110;
  wire s111;
  wire s112;
  wire s113;
  wire s114;
  wire s115;
  wire s116;
  wire s117;
  wire s118;
  wire s119;
  wire s120;
  wire s121;
  wire s122;
  wire s123;
  wire s124;
  wire s125;
  wire s126;
  wire s127;
  wire s128;
  wire s129;
  wire s130;
  wire s131;
  wire s132;
  wire s133;
  wire s134;
  wire s135;
  wire s136;
  wire s137;
  wire s138;
  wire s139;
  wire s140;
  wire s141;
  wire s142;
  wire s143;
  wire s144;
  wire s145;
  wire s146;
  wire s147;
  wire s148;
  wire s149;
  wire s150;
  wire s151;
  wire s152;
  wire s153;
  wire s154;
  wire s155;
  wire s156;
  wire s157;
  wire s158;
  wire s159;
  wire s160;
  wire s161;
  wire s162;
  wire s163;
  wire s164;
  wire s165;
  wire s166;
  wire s167;
  wire s168;
  wire s169;
  wire s170;
  wire s171;
  wire s172;
  wire s173;
  wire s174;
  wire s175;
  wire s176;
  wire s177;
  wire s178;
  wire s179;
  wire s180;
  wire s181;
  wire s182;
  wire s183;
  wire s184;
  wire s185;
  wire s186;
  wire s187;
  wire s188;
  wire s189;
  wire s190;
  wire s191;
  wire s192;
  wire s193;
  wire s194;
  wire s195;
  wire s196;
  wire s197;
  wire s198;
  wire s199;
  wire s200;
  wire s201;
  wire s202;
  wire s203;
  wire s204;
  wire s205;
  wire s206;
  wire s207;
  wire s208;
  wire s209;
  wire s210;
  wire s211;
  wire s212;
  wire s213;
  wire s214;
  wire s215;
  wire s216;
  wire s217;
  wire s218;
  wire s219;
  wire s220;
  wire s221;
  wire s222;
  wire s223;
  wire s224;
  wire s225;
  wire s226;
  wire s227;
  wire s228;
  wire s229;
  wire s230;
  wire s231;
  wire s232;
  wire s233;
  wire s234;
  wire s235;
  wire s236;
  wire s237;
  wire s238;
  wire s239;
  wire s240;
  wire s241;
  wire s242;
  wire s243;
  wire s244;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i0 (
    .D( B3 ),
    .C( CLK ),
    .Q( s0 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i1 (
    .D( B2 ),
    .C( CLK ),
    .Q( s3 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i2 (
    .D( B1 ),
    .C( CLK ),
    .Q( s5 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i3 (
    .D( B0 ),
    .C( CLK ),
    .Q( s7 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i4 (
    .D( HZ1 ),
    .C( CLK ),
    .Q( s9 )
  );
  assign s13 = ~ SW;
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i5 (
    .D( 1'b1 ),
    .C( CLK ),
    .Q( s237 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i6 (
    .D( 1'b1 ),
    .C( CLK ),
    .Q( s239 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i7 (
    .D( 1'b1 ),
    .C( CLK ),
    .Q( s241 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i8 (
    .D( 1'b1 ),
    .C( CLK ),
    .Q( s243 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i9 (
    .D( s0 ),
    .C( CLK ),
    .\~Q ( s2 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i10 (
    .D( s3 ),
    .C( CLK ),
    .\~Q ( s4 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i11 (
    .D( s5 ),
    .C( CLK ),
    .\~Q ( s6 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i12 (
    .D( s7 ),
    .C( CLK ),
    .\~Q ( s8 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i13 (
    .D( s9 ),
    .C( CLK ),
    .\~Q ( s11 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i14 (
    .D( s237 ),
    .C( CLK ),
    .Q( s238 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i15 (
    .D( s239 ),
    .C( CLK ),
    .Q( s240 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i16 (
    .D( s241 ),
    .C( CLK ),
    .Q( s242 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i17 (
    .D( s243 ),
    .C( CLK ),
    .Q( s244 )
  );
  assign s12 = (s9 & s11);
  assign s16 = (((s7 & s8) & SW) & s238);
  assign s36 = (s240 & (SW & (s5 & s6)));
  assign s52 = (s242 & (SW & (s3 & s4)));
  assign s74 = (s244 & (SW & (s0 & s2)));
  assign s113 = (s13 & s12);
  assign s128 = (s13 & s12);
  assign s149 = (s13 & s12);
  assign s170 = (s12 & s13);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i18 (
    .D( s14 ),
    .C( CLK ),
    .Q( s15 )
  );
  assign s17 = (s16 ^ s15);
  assign s18 = (s16 & s15);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i19 (
    .D( s21 ),
    .C( CLK ),
    .Q( s19 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i20 (
    .D( s25 ),
    .C( CLK ),
    .Q( s23 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i21 (
    .D( s28 ),
    .C( CLK ),
    .Q( s26 )
  );
  assign s38 = (s36 ^ s37);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i22 (
    .D( s39 ),
    .C( CLK ),
    .Q( s37 )
  );
  assign s40 = (s36 & s37);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i23 (
    .D( s43 ),
    .C( CLK ),
    .Q( s41 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i24 (
    .D( s46 ),
    .C( CLK ),
    .Q( s44 )
  );
  assign s54 = (s52 ^ s53);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i25 (
    .D( s55 ),
    .C( CLK ),
    .Q( s53 )
  );
  assign s56 = (s52 & s53);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i26 (
    .D( s59 ),
    .C( CLK ),
    .Q( s57 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i27 (
    .D( s63 ),
    .C( CLK ),
    .Q( s61 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i28 (
    .D( s66 ),
    .C( CLK ),
    .Q( s64 )
  );
  assign s76 = (s74 ^ s75);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i29 (
    .D( s77 ),
    .C( CLK ),
    .Q( s75 )
  );
  assign s78 = (s74 & s75);
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i30 (
    .D( s81 ),
    .C( CLK ),
    .Q( s79 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i31 (
    .D( s85 ),
    .C( CLK ),
    .Q( s83 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i32 (
    .D( s88 ),
    .C( CLK ),
    .Q( s86 )
  );
  Mux_2x1 Mux_2x1_i33 (
    .sel( s113 ),
    .in_0( s32 ),
    .in_1( s114 ),
    .out( s14 )
  );
  Mux_2x1 Mux_2x1_i34 (
    .sel( s113 ),
    .in_0( s33 ),
    .in_1( s115 ),
    .out( s21 )
  );
  Mux_2x1 Mux_2x1_i35 (
    .sel( s113 ),
    .in_0( s34 ),
    .in_1( s116 ),
    .out( s25 )
  );
  Mux_2x1 Mux_2x1_i36 (
    .sel( s113 ),
    .in_0( s35 ),
    .in_1( s117 ),
    .out( s28 )
  );
  Mux_2x1 Mux_2x1_i37 (
    .sel( s128 ),
    .in_0( s51 ),
    .in_1( s129 ),
    .out( s46 )
  );
  Mux_2x1 Mux_2x1_i38 (
    .sel( s128 ),
    .in_0( s50 ),
    .in_1( s130 ),
    .out( s43 )
  );
  Mux_2x1 Mux_2x1_i39 (
    .sel( s128 ),
    .in_0( s49 ),
    .in_1( s131 ),
    .out( s39 )
  );
  Mux_2x1 Mux_2x1_i40 (
    .sel( s149 ),
    .in_0( s70 ),
    .in_1( s150 ),
    .out( s55 )
  );
  Mux_2x1 Mux_2x1_i41 (
    .sel( s149 ),
    .in_0( s71 ),
    .in_1( s151 ),
    .out( s59 )
  );
  Mux_2x1 Mux_2x1_i42 (
    .sel( s149 ),
    .in_0( s72 ),
    .in_1( s152 ),
    .out( s63 )
  );
  Mux_2x1 Mux_2x1_i43 (
    .sel( s149 ),
    .in_0( s73 ),
    .in_1( s153 ),
    .out( s66 )
  );
  Mux_2x1 Mux_2x1_i44 (
    .sel( s170 ),
    .in_0( s92 ),
    .in_1( s171 ),
    .out( s77 )
  );
  Mux_2x1 Mux_2x1_i45 (
    .sel( s170 ),
    .in_0( s93 ),
    .in_1( s172 ),
    .out( s81 )
  );
  Mux_2x1 Mux_2x1_i46 (
    .sel( s170 ),
    .in_0( s94 ),
    .in_1( s173 ),
    .out( s85 )
  );
  Mux_2x1 Mux_2x1_i47 (
    .sel( s170 ),
    .in_0( s95 ),
    .in_1( s174 ),
    .out( s88 )
  );
  DIG_D_FF_1bit #(
    .Default(0)
  )
  DIG_D_FF_1bit_i48 (
    .D( s175 ),
    .C( CLK ),
    .Q( s176 )
  );
  assign s175 = ((s13 & ((s30 & ~ s19 & s29 & ~ s26) & (s47 & ~ s41 & ~ s44 & 1'b1) & (s67 & ~ s57 & s68 & ~ s64) & (s89 & ~ s79 & s90 & ~ s86))) | s176);
  assign s20 = (s18 ^ s19);
  assign s22 = (s18 & s19);
  assign S1_temp[0] = s15;
  assign S1_temp[1] = s19;
  assign S1_temp[2] = s23;
  assign S1_temp[3] = s26;
  assign s29 = ~ s23;
  assign s30 = ~ s15;
  assign s42 = (s40 ^ s41);
  assign s45 = ((s40 & s41) ^ s44);
  assign s47 = ~ s37;
  assign S10_temp[0] = s37;
  assign S10_temp[1] = s41;
  assign S10_temp[2] = s44;
  assign S10_temp[3] = 1'b0;
  assign s58 = (s56 ^ s57);
  assign s60 = (s56 & s57);
  assign s67 = ~ s53;
  assign s68 = ~ s61;
  assign M1_temp[0] = s53;
  assign M1_temp[1] = s57;
  assign M1_temp[2] = s61;
  assign M1_temp[3] = s64;
  assign s80 = (s78 ^ s79);
  assign s82 = (s78 & s79);
  assign s89 = ~ s75;
  assign s90 = ~ s83;
  assign M10_temp[0] = s75;
  assign M10_temp[1] = s79;
  assign M10_temp[2] = s83;
  assign M10_temp[3] = s86;
  assign s24 = (s22 ^ s23);
  assign s27 = ((s22 & s23) ^ s26);
  assign s31 = (s30 & s19 & s29 & s26);
  assign s48 = (s47 & s41 & s44);
  assign s62 = (s60 ^ s61);
  assign s65 = ((s60 & s61) ^ s64);
  assign s69 = (s64 & s68 & s57 & s67);
  assign s84 = (s82 ^ s83);
  assign s87 = ((s82 & s83) ^ s86);
  assign s91 = (s86 & s90 & s79 & s89);
  assign s96 = S1_temp[0];
  assign s97 = S1_temp[1];
  assign s98 = S1_temp[2];
  assign s99 = S1_temp[3];
  assign s132 = M1_temp[0];
  assign s133 = M1_temp[1];
  assign s134 = M1_temp[2];
  assign s135 = M1_temp[3];
  assign s154 = M10_temp[0];
  assign s155 = M10_temp[1];
  assign s156 = M10_temp[2];
  assign s157 = M10_temp[3];
  assign s177 = S1_temp[0];
  assign s178 = S1_temp[1];
  assign s179 = S1_temp[2];
  assign s180 = S1_temp[3];
  assign s193 = S10_temp[0];
  assign s194 = S10_temp[1];
  assign s195 = S10_temp[2];
  assign s205 = M1_temp[0];
  assign s206 = M1_temp[1];
  assign s207 = M1_temp[2];
  assign s208 = M1_temp[3];
  assign s221 = M10_temp[0];
  assign s222 = M10_temp[1];
  assign s223 = M10_temp[2];
  assign s224 = M10_temp[3];
  Mux_2x1 Mux_2x1_i49 (
    .sel( s31 ),
    .in_0( s17 ),
    .in_1( 1'b0 ),
    .out( s32 )
  );
  Mux_2x1 Mux_2x1_i50 (
    .sel( s31 ),
    .in_0( s20 ),
    .in_1( 1'b0 ),
    .out( s33 )
  );
  Mux_2x1 Mux_2x1_i51 (
    .sel( s31 ),
    .in_0( s24 ),
    .in_1( 1'b0 ),
    .out( s34 )
  );
  Mux_2x1 Mux_2x1_i52 (
    .sel( s31 ),
    .in_0( s27 ),
    .in_1( 1'b0 ),
    .out( s35 )
  );
  Mux_2x1 Mux_2x1_i53 (
    .sel( s48 ),
    .in_0( s38 ),
    .in_1( 1'b0 ),
    .out( s49 )
  );
  Mux_2x1 Mux_2x1_i54 (
    .sel( s48 ),
    .in_0( s42 ),
    .in_1( 1'b0 ),
    .out( s50 )
  );
  Mux_2x1 Mux_2x1_i55 (
    .sel( s48 ),
    .in_0( s45 ),
    .in_1( 1'b0 ),
    .out( s51 )
  );
  Mux_2x1 Mux_2x1_i56 (
    .sel( s69 ),
    .in_0( s54 ),
    .in_1( 1'b0 ),
    .out( s70 )
  );
  Mux_2x1 Mux_2x1_i57 (
    .sel( s69 ),
    .in_0( s58 ),
    .in_1( 1'b0 ),
    .out( s71 )
  );
  Mux_2x1 Mux_2x1_i58 (
    .sel( s69 ),
    .in_0( s62 ),
    .in_1( 1'b0 ),
    .out( s72 )
  );
  Mux_2x1 Mux_2x1_i59 (
    .sel( s69 ),
    .in_0( s65 ),
    .in_1( 1'b0 ),
    .out( s73 )
  );
  Mux_2x1 Mux_2x1_i60 (
    .sel( s91 ),
    .in_0( s76 ),
    .in_1( 1'b0 ),
    .out( s92 )
  );
  Mux_2x1 Mux_2x1_i61 (
    .sel( s91 ),
    .in_0( s80 ),
    .in_1( 1'b0 ),
    .out( s93 )
  );
  Mux_2x1 Mux_2x1_i62 (
    .sel( s91 ),
    .in_0( s84 ),
    .in_1( 1'b0 ),
    .out( s94 )
  );
  Mux_2x1 Mux_2x1_i63 (
    .sel( s91 ),
    .in_0( s87 ),
    .in_1( 1'b0 ),
    .out( s95 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i64 (
    .a( s96 ),
    .b( 1'b1 ),
    .c_i( 1'b0 ),
    .s( s100 ),
    .c_o( s101 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i65 (
    .a( s177 ),
    .b( 1'b1 ),
    .c_i( 1'b0 ),
    .s( s181 ),
    .c_o( s182 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i66 (
    .a( s97 ),
    .b( 1'b1 ),
    .c_i( s101 ),
    .s( s102 ),
    .c_o( s103 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i67 (
    .a( s178 ),
    .b( 1'b0 ),
    .c_i( s182 ),
    .s( s183 ),
    .c_o( s184 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i68 (
    .a( s98 ),
    .b( 1'b1 ),
    .c_i( s103 ),
    .s( s104 ),
    .c_o( s105 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i69 (
    .a( s179 ),
    .b( 1'b0 ),
    .c_i( s184 ),
    .s( s185 ),
    .c_o( s186 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i70 (
    .a( s99 ),
    .b( 1'b1 ),
    .c_i( s105 ),
    .s( s106 ),
    .c_o( s107 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i71 (
    .a( s180 ),
    .b( 1'b0 ),
    .c_i( s186 ),
    .s( s187 )
  );
  assign s108 = (s100 & s102 & s104 & s106);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i72 (
    .a( s37 ),
    .b( 1'b1 ),
    .c_i( s107 ),
    .s( s118 ),
    .c_o( s119 )
  );
  assign s188 = (~ s181 & s183 & ~ s185 & s187);
  Mux_2x1 Mux_2x1_i73 (
    .sel( s108 ),
    .in_0( s100 ),
    .in_1( 1'b1 ),
    .out( s109 )
  );
  Mux_2x1 Mux_2x1_i74 (
    .sel( s108 ),
    .in_0( s102 ),
    .in_1( 1'b0 ),
    .out( s110 )
  );
  Mux_2x1 Mux_2x1_i75 (
    .sel( s108 ),
    .in_0( s104 ),
    .in_1( 1'b0 ),
    .out( s111 )
  );
  Mux_2x1 Mux_2x1_i76 (
    .sel( s108 ),
    .in_0( s106 ),
    .in_1( 1'b1 ),
    .out( s112 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i77 (
    .a( s41 ),
    .b( 1'b1 ),
    .c_i( s119 ),
    .s( s120 ),
    .c_o( s121 )
  );
  Mux_2x1 Mux_2x1_i78 (
    .sel( s188 ),
    .in_0( s181 ),
    .in_1( 1'b0 ),
    .out( s189 )
  );
  Mux_2x1 Mux_2x1_i79 (
    .sel( s188 ),
    .in_0( s183 ),
    .in_1( 1'b0 ),
    .out( s190 )
  );
  Mux_2x1 Mux_2x1_i80 (
    .sel( s188 ),
    .in_0( s185 ),
    .in_1( 1'b0 ),
    .out( s191 )
  );
  Mux_2x1 Mux_2x1_i81 (
    .sel( s188 ),
    .in_0( s187 ),
    .in_1( 1'b0 ),
    .out( s192 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i82 (
    .a( s193 ),
    .b( s188 ),
    .c_i( 1'b0 ),
    .s( s196 ),
    .c_o( s197 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i83 (
    .a( s44 ),
    .b( 1'b1 ),
    .c_i( s121 ),
    .s( s122 ),
    .c_o( s123 )
  );
  Mux_2x1 Mux_2x1_i84 (
    .sel( s176 ),
    .in_0( s109 ),
    .in_1( s189 ),
    .out( s114 )
  );
  Mux_2x1 Mux_2x1_i85 (
    .sel( s176 ),
    .in_0( s110 ),
    .in_1( s190 ),
    .out( s115 )
  );
  Mux_2x1 Mux_2x1_i86 (
    .sel( s176 ),
    .in_0( s111 ),
    .in_1( s191 ),
    .out( s116 )
  );
  Mux_2x1 Mux_2x1_i87 (
    .sel( s176 ),
    .in_0( s112 ),
    .in_1( s192 ),
    .out( s117 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i88 (
    .a( s194 ),
    .b( 1'b0 ),
    .c_i( s197 ),
    .s( s198 ),
    .c_o( s199 )
  );
  assign s124 = (s118 & s120 & s122);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i89 (
    .a( s132 ),
    .b( 1'b1 ),
    .c_i( s123 ),
    .s( s136 ),
    .c_o( s137 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i90 (
    .a( s195 ),
    .b( 1'b0 ),
    .c_i( s199 ),
    .s( s200 )
  );
  Mux_2x1 Mux_2x1_i91 (
    .sel( s124 ),
    .in_0( s118 ),
    .in_1( 1'b1 ),
    .out( s125 )
  );
  Mux_2x1 Mux_2x1_i92 (
    .sel( s124 ),
    .in_0( s120 ),
    .in_1( 1'b0 ),
    .out( s126 )
  );
  Mux_2x1 Mux_2x1_i93 (
    .sel( s124 ),
    .in_0( s122 ),
    .in_1( 1'b1 ),
    .out( s127 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i94 (
    .a( s133 ),
    .b( 1'b1 ),
    .c_i( s137 ),
    .s( s138 ),
    .c_o( s139 )
  );
  assign s201 = (~ s196 & s198 & s200);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i95 (
    .a( s134 ),
    .b( 1'b1 ),
    .c_i( s139 ),
    .s( s140 ),
    .c_o( s141 )
  );
  Mux_2x1 Mux_2x1_i96 (
    .sel( s201 ),
    .in_0( s196 ),
    .in_1( 1'b0 ),
    .out( s202 )
  );
  Mux_2x1 Mux_2x1_i97 (
    .sel( s201 ),
    .in_0( s198 ),
    .in_1( 1'b0 ),
    .out( s203 )
  );
  Mux_2x1 Mux_2x1_i98 (
    .sel( s201 ),
    .in_0( s200 ),
    .in_1( 1'b0 ),
    .out( s204 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i99 (
    .a( s205 ),
    .b( s201 ),
    .c_i( 1'b0 ),
    .s( s209 ),
    .c_o( s210 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i100 (
    .a( s135 ),
    .b( 1'b1 ),
    .c_i( s141 ),
    .s( s142 ),
    .c_o( s143 )
  );
  Mux_2x1 Mux_2x1_i101 (
    .sel( s176 ),
    .in_0( s125 ),
    .in_1( s202 ),
    .out( s131 )
  );
  Mux_2x1 Mux_2x1_i102 (
    .sel( s176 ),
    .in_0( s126 ),
    .in_1( s203 ),
    .out( s130 )
  );
  Mux_2x1 Mux_2x1_i103 (
    .sel( s176 ),
    .in_0( s127 ),
    .in_1( s204 ),
    .out( s129 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i104 (
    .a( s206 ),
    .b( 1'b0 ),
    .c_i( s210 ),
    .s( s211 ),
    .c_o( s212 )
  );
  assign s144 = (s136 & s138 & s140 & s142);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i105 (
    .a( s154 ),
    .b( 1'b1 ),
    .c_i( s143 ),
    .s( s158 ),
    .c_o( s159 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i106 (
    .a( s207 ),
    .b( 1'b0 ),
    .c_i( s212 ),
    .s( s213 ),
    .c_o( s214 )
  );
  Mux_2x1 Mux_2x1_i107 (
    .sel( s144 ),
    .in_0( s138 ),
    .in_1( 1'b0 ),
    .out( s145 )
  );
  Mux_2x1 Mux_2x1_i108 (
    .sel( s144 ),
    .in_0( s136 ),
    .in_1( 1'b1 ),
    .out( s146 )
  );
  Mux_2x1 Mux_2x1_i109 (
    .sel( s144 ),
    .in_0( s140 ),
    .in_1( 1'b0 ),
    .out( s147 )
  );
  Mux_2x1 Mux_2x1_i110 (
    .sel( s144 ),
    .in_0( s142 ),
    .in_1( 1'b1 ),
    .out( s148 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i111 (
    .a( s155 ),
    .b( 1'b1 ),
    .c_i( s159 ),
    .s( s160 ),
    .c_o( s161 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i112 (
    .a( s208 ),
    .b( 1'b0 ),
    .c_i( s214 ),
    .s( s215 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i113 (
    .a( s156 ),
    .b( 1'b1 ),
    .c_i( s161 ),
    .s( s162 ),
    .c_o( s163 )
  );
  assign s216 = (~ s209 & s211 & ~ s213 & s215);
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i114 (
    .a( s157 ),
    .b( 1'b1 ),
    .c_i( s163 ),
    .s( s164 )
  );
  Mux_2x1 Mux_2x1_i115 (
    .sel( s216 ),
    .in_0( s209 ),
    .in_1( 1'b0 ),
    .out( s217 )
  );
  Mux_2x1 Mux_2x1_i116 (
    .sel( s216 ),
    .in_0( s211 ),
    .in_1( 1'b0 ),
    .out( s218 )
  );
  Mux_2x1 Mux_2x1_i117 (
    .sel( s216 ),
    .in_0( s213 ),
    .in_1( 1'b0 ),
    .out( s219 )
  );
  Mux_2x1 Mux_2x1_i118 (
    .sel( s216 ),
    .in_0( s215 ),
    .in_1( 1'b0 ),
    .out( s220 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i119 (
    .a( s221 ),
    .b( s216 ),
    .c_i( 1'b0 ),
    .s( s225 ),
    .c_o( s226 )
  );
  assign s165 = (s158 & s160 & s162 & s164);
  Mux_2x1 Mux_2x1_i120 (
    .sel( s176 ),
    .in_0( s146 ),
    .in_1( s217 ),
    .out( s150 )
  );
  Mux_2x1 Mux_2x1_i121 (
    .sel( s176 ),
    .in_0( s145 ),
    .in_1( s218 ),
    .out( s151 )
  );
  Mux_2x1 Mux_2x1_i122 (
    .sel( s176 ),
    .in_0( s147 ),
    .in_1( s219 ),
    .out( s152 )
  );
  Mux_2x1 Mux_2x1_i123 (
    .sel( s176 ),
    .in_0( s148 ),
    .in_1( s220 ),
    .out( s153 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i124 (
    .a( s222 ),
    .b( 1'b0 ),
    .c_i( s226 ),
    .s( s227 ),
    .c_o( s228 )
  );
  Mux_2x1 Mux_2x1_i125 (
    .sel( s165 ),
    .in_0( s158 ),
    .in_1( 1'b1 ),
    .out( s166 )
  );
  Mux_2x1 Mux_2x1_i126 (
    .sel( s165 ),
    .in_0( s160 ),
    .in_1( 1'b0 ),
    .out( s167 )
  );
  Mux_2x1 Mux_2x1_i127 (
    .sel( s165 ),
    .in_0( s162 ),
    .in_1( 1'b0 ),
    .out( s168 )
  );
  Mux_2x1 Mux_2x1_i128 (
    .sel( s165 ),
    .in_0( s164 ),
    .in_1( 1'b1 ),
    .out( s169 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i129 (
    .a( s223 ),
    .b( 1'b0 ),
    .c_i( s228 ),
    .s( s229 ),
    .c_o( s230 )
  );
  DIG_Add #(
    .Bits(1)
  )
  DIG_Add_i130 (
    .a( s224 ),
    .b( 1'b0 ),
    .c_i( s230 ),
    .s( s231 )
  );
  assign s232 = (~ s225 & s227 & ~ s229 & s231);
  Mux_2x1 Mux_2x1_i131 (
    .sel( s232 ),
    .in_0( s225 ),
    .in_1( 1'b0 ),
    .out( s233 )
  );
  Mux_2x1 Mux_2x1_i132 (
    .sel( s232 ),
    .in_0( s227 ),
    .in_1( 1'b0 ),
    .out( s234 )
  );
  Mux_2x1 Mux_2x1_i133 (
    .sel( s232 ),
    .in_0( s229 ),
    .in_1( 1'b0 ),
    .out( s235 )
  );
  Mux_2x1 Mux_2x1_i134 (
    .sel( s232 ),
    .in_0( s231 ),
    .in_1( 1'b0 ),
    .out( s236 )
  );
  Mux_2x1 Mux_2x1_i135 (
    .sel( s176 ),
    .in_0( s166 ),
    .in_1( s233 ),
    .out( s171 )
  );
  Mux_2x1 Mux_2x1_i136 (
    .sel( s176 ),
    .in_0( s167 ),
    .in_1( s234 ),
    .out( s172 )
  );
  Mux_2x1 Mux_2x1_i137 (
    .sel( s176 ),
    .in_0( s168 ),
    .in_1( s235 ),
    .out( s173 )
  );
  Mux_2x1 Mux_2x1_i138 (
    .sel( s176 ),
    .in_0( s169 ),
    .in_1( s236 ),
    .out( s174 )
  );
  assign M10 = M10_temp;
  assign M1 = M1_temp;
  assign S10 = S10_temp;
  assign S1 = S1_temp;
endmodule
